/* Generated by odin -backend:plan9-c — do not edit. */
/* entry point: main (package main) */
#include "odin_generated.h"

void
write_cstr(char *s)
{
	sys_write(1, (unsigned char*)s, sys_strlen(s));
	return;
}

void
main()
{
	char *hello;
	char *extra;
	int n;
	hello = "hello from odin plan9\n";
	extra = "!\n";
	n = sys_strlen(hello);
	if ((n > 0)) {
		write_cstr(hello);
	}
	int i;
	for (i = 0; (i < 1); i += 1) {
		write_cstr(extra);
	}
	return;
}

int
odin_main(int argc, char **argv)
{
	USED(argc);
	USED(argv);
	main();
	return 0;
}
