/* Generated by odin -backend:plan9-c — do not edit. */
/* entry point: main (package main) */
#include "odin_generated.h"

typedef struct odin_Point odin_Point;
struct odin_Point {
	int x;
	int y;
};

typedef struct odin_string odin_string;
struct odin_string {
	unsigned char *data;
	long len;
};

static void odin_user_main(void);

void
write_cstr(char *s)
{
	sys_write(1, (unsigned char*)s, sys_strlen(s));
	return;
}

int
point_sum(odin_Point p)
{
	return (p.x + p.y);
}

static void
odin_user_main(void)
{
	odin_Point p;
	int n;
	int i;
	p.x = 1;
	p.y = 2;
	n = 0;
	switch (point_sum(p)) {
		case 0:
			n = 0;
		break;
		case 3:
			n = 1;
		break;
		default:
			n = -1;
		break;
	}
	if ((n == 1)) {
		write_cstr("hello adv plan9\n");
	}
	for (i = 0; (i < 2); i += 1) {
		write_cstr("!\n");
	}
	return;
}

int
odin_main(int argc, char **argv)
{
	USED(argc);
	USED(argv);
	odin_user_main();
	return 0;
}
