/* Generated by odin -backend:plan9-c — do not edit. */
/* entry point: main (package main) */
#include "odin_generated.h"

extern int sys_strlen(char *s);
extern int sys_write(int fd, unsigned char* buf, int count);

int
odin_main(int argc, char **argv)
{
	USED(argc);
	USED(argv);
	char *msg;
	msg = "hello from odin plan9\n";
	sys_write(1, (unsigned char*)msg, sys_strlen(msg));
	return 0;
}
