#include <u.h>
#include <libc.h>
#include <bio.h>

static void
emit_hello(Biobuf *out)
{
	Bprint(out, "/* Generated by cgen hello — do not edit. */\n");
	Bprint(out, "#include \"odin_generated.h\"\n");
	Bprint(out, "\n");
	Bprint(out, "int\n");
	Bprint(out, "odin_main(int argc, char **argv)\n");
	Bprint(out, "{\n");
	Bprint(out, "\tchar *msg;\n");
	Bprint(out, "\n");
	Bprint(out, "\tUSED(argc);\n");
	Bprint(out, "\tUSED(argv);\n");
	Bprint(out, "\tmsg = \"hello from odin plan9\\n\";\n");
	Bprint(out, "\tsys_write(1, msg, sys_strlen(msg));\n");
	Bprint(out, "\treturn 0;\n");
	Bprint(out, "}\n");
}

void
usage(void)
{
	fprint(2, "usage: cgen hello\n");
	exits("usage");
}

void
main(int argc, char **argv)
{
	Biobuf out;

	USED(argc);
	if(argv[1] == nil || argv[2] != nil || strcmp(argv[1], "hello") != 0)
		usage();

	Binit(&out, 1, OWRITE);
	emit_hello(&out);
	Bterm(&out);
	exits(nil);
}
