/* Generated by odin -backend:plan9-c — do not edit. */
/* entry point: main (package main) */
#include "odin_generated.h"

typedef struct odin_string odin_string;
struct odin_string {
	unsigned char *data;
	long len;
};

static void odin_user_main(void);
int _write_string(odin_string s);
int println(odin_string s);

static void
odin_user_main(void)
{
	println(((odin_string){(unsigned char*)"hello from odin plan9 fmt", 25}));
	return;
}

int
_write_string(odin_string s)
{
	if (((s.len) == 0)) {
		return 0;
	}
	return sys_write(1, (unsigned char*)s.data, (s.len));
}

int
println(odin_string s)
{
	int n;
	n = _write_string(s);
	n += _write_string(((odin_string){(unsigned char*)"\n", 1}));
	return n;
}

int
odin_main(int argc, char **argv)
{
	USED(argc);
	USED(argv);
	odin_user_main();
	return 0;
}
