# Plan 9 mkfile for libodin_plan9.a
# Run on 9front: cd core/os/plan9 && mk

</$objtype/mkfile

SRC=src
LIB=libodin_plan9.a
CFLAGS=-I$SRC
LIBTHREAD=/$objtype/lib/libthread.a

RUNTIME=../../../sys/src/cmd/odin_runtime/plan9

OFILES=\
	sysdeps.$O\
	mem.$O\
	filesys.$O\
	path.$O\
	dir.$O\
	env.$O\
	process.$O\
	time.$O\
	mmap.$O\
	sys_thread.$O\
	net.$O\

HFILES=\
	$SRC/common.h\
	$SRC/sysdeps.h\
	$SRC/mem.h\
	$SRC/filesys.h\
	$SRC/path.h\
	$SRC/dir.h\
	$SRC/env.h\
	$SRC/process.h\
	$SRC/sys_time.h\
	$SRC/mmap.h\
	$SRC/sys_thread.h\
	$SRC/net.h\

all:V: $LIB test_filesys test_path test_dir test_env test_mmap test_thread test_net hello

$LIB: $OFILES
	ar vu $LIB $OFILES

sysdeps.$O: $SRC/sysdeps.c $HFILES
	$CC $CFLAGS -o $target $SRC/sysdeps.c

mem.$O: $SRC/mem.c $HFILES
	$CC $CFLAGS -o $target $SRC/mem.c

filesys.$O: $SRC/filesys.c $HFILES
	$CC $CFLAGS -o $target $SRC/filesys.c

path.$O: $SRC/path.c $HFILES
	$CC $CFLAGS -o $target $SRC/path.c

dir.$O: $SRC/dir.c $HFILES
	$CC $CFLAGS -o $target $SRC/dir.c

env.$O: $SRC/env.c $HFILES
	$CC $CFLAGS -o $target $SRC/env.c

process.$O: $SRC/process.c $HFILES
	$CC $CFLAGS -o $target $SRC/process.c

time.$O: $SRC/time.c $HFILES
	$CC $CFLAGS -o $target $SRC/time.c

mmap.$O: $SRC/mmap.c $HFILES
	$CC $CFLAGS -o $target $SRC/mmap.c

sys_thread.$O: $SRC/sys_thread.c $HFILES
	$CC $CFLAGS -o $target $SRC/sys_thread.c

net.$O: $SRC/net.c $HFILES
	$CC $CFLAGS -o $target $SRC/net.c

test_filesys.$O: $SRC/test_filesys.c $HFILES
	$CC $CFLAGS -o $target $SRC/test_filesys.c

test_filesys: test_filesys.$O $LIB
	$LD -o $target test_filesys.$O $LIB

test_path.$O: $SRC/test_path.c $HFILES
	$CC $CFLAGS -o $target $SRC/test_path.c

test_path: test_path.$O $LIB
	$LD -o $target test_path.$O $LIB

test_dir.$O: $SRC/test_dir.c $HFILES
	$CC $CFLAGS -o $target $SRC/test_dir.c

test_dir: test_dir.$O $LIB
	$LD -o $target test_dir.$O $LIB

test_env.$O: $SRC/test_env.c $HFILES
	$CC $CFLAGS -o $target $SRC/test_env.c

test_env: test_env.$O $LIB
	$LD -o $target test_env.$O $LIB

test_mmap.$O: $SRC/test_mmap.c $HFILES
	$CC $CFLAGS -o $target $SRC/test_mmap.c

test_mmap: test_mmap.$O $LIB
	$LD -o $target test_mmap.$O $LIB

test_thread.$O: $SRC/test_thread.c $HFILES
	$CC $CFLAGS -o $target $SRC/test_thread.c

test_thread: test_thread.$O $LIB
	$LD -o $target test_thread.$O $LIB $LIBTHREAD

test_net.$O: $SRC/test_net.c $HFILES
	$CC $CFLAGS -o $target $SRC/test_net.c

test_net: test_net.$O $LIB
	$LD -o $target test_net.$O $LIB $LIBTHREAD

hello.$O: $SRC/hello.c $HFILES
	$CC $CFLAGS -o $target $SRC/hello.c

entry.$O: $RUNTIME/entry.c $HFILES
	$CC $CFLAGS -I$SRC -o $target $RUNTIME/entry.c

hello: hello.$O entry.$O $LIB
	$LD -o $target hello.$O entry.$O $LIB

clean:V:
	rm -f *.$O [$O].out $LIB test_filesys test_path test_dir test_env test_mmap test_thread test_net hello entry.$O

install:V: $LIB
	cp $LIB /$objtype/lib/

.DEFAULT:
	$CC $CFLAGS -o $O $stem.c
